#!/usr/bin/env bash
#
export _JAVA_AWT_WM_NONREPARENTING=1

xrandr --output DP-0 --primary --mode 2560x1440 --rate 144.00 --output DP-2 --mode 2560x1440 --rate 144.00 --left-of DP-0

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor

bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


# Rules
bspc rule -r '*'
bspc rule -a sun-awt-X11-XDialogPeer state=floating
bspc rule -a Pinentry state=floating center=on
bspc rule -a Emacs state=tiled
bspc rule -a PureRef state=floating center=on rectangle=1800x1200+0+0
bspc rule -a Firefox split_ratio=0.32
bspc rule -a feh state=fullscreen
# bspc rule -a jetbrains-idea state=floating
bspc rule -a jetbrains-clion state=floating
bspc rule -a Zotero state=floating
bspc rule -a Anki state=floating
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1800x1200+0+0
