source $ZDOTDIR/config.zsh

if [ ! -d "$ZGEN_DIR" ]; then
  echo "Installing jandamm/zgenom"
  git clone https://github.com/jandamm/zgenom "$ZGEN_DIR"
fi
source $ZGEN_DIR/zgenom.zsh
zgenom autoupdate

if ! zgenom saved; then
  echo "Initializing zgenom"
  rm -f $ZDOTDIR/*.zwc(N) \
        $XDG_CACHE_HOME/zsh/*(N) \
        $ZGEN_INIT.zwc

  zgenom load junegunn/fzf shell
  zgenom load jeffreytse/zsh-vi-mode
  zgenom load zdharma-continuum/fast-syntax-highlighting
  zgenom load zsh-users/zsh-completions src
  zgenom load zsh-users/zsh-autosuggestions
  zgenom load zsh-users/zsh-history-substring-search
  zgenom load romkatv/powerlevel10k powerlevel10k
  zgenom load hlissner/zsh-autopair autopair.zsh

  zgenom save
  zgenom compile $ZDOTDIR
fi


if [[ $TERM != dumb ]]; then
	autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump

	source $ZDOTDIR/keybinds.zsh
	source $ZDOTDIR/completion.zsh
	source $ZDOTDIR/aliases.zsh

	## Auto-generated by my nix config
	[ -f $ZDOTDIR/extra.zshrc ] && source $ZDOTDIR/extra.zshrc

	_cache fasd --init posix-alias zsh-{hook,{c,w}comp{,-install}}
	autopair-init
	eval "$(direnv hook zsh)"
fi
